max_energy: 100000
energy_per_tick: 100
fly_speed: 0.03
armor: 3.0

enchantment_value: 15
supported_enchantments:
  - minecraft:protection
  - minecraft:fire_protection
  - minecraft:blast_protection
  - minecraft:projectile_protection
  - minecraft:thorns